---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-full-access
  namespace: api
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-full-access
  namespace: web
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-view-access
  namespace: api
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-view-access
  namespace: web
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-full-access-rb
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-full-access
subjects:
- kind: Group
  namespace: api
  name: 8e4c558e-5a7a-4419-a95c-c39289feb531

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-view-access-rb
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-view-access
subjects:
- kind: Group
  namespace: web
  name: 8e4c558e-5a7a-4419-a95c-c39289feb531

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-full-access-rb
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-full-access
subjects:
- kind: Group
  namespace: web
  name: 22982c26-4625-42f1-956c-f8d36d170029

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-view-access-rb
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-view-access
subjects:
- kind: Group
  namespace: api
  name: 22982c26-4625-42f1-956c-f8d36d170029