apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-network-policy
  namespace: api
spec:
  podSelector:
    matchLabels:
      app: user-deployment
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: web
    - podSelector:
        matchLabels:
          app: tripviewer-deployment

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: trips-network-policy
  namespace: api
spec:
  podSelector:
    matchLabels:
      app: trips-deployment
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: web
    - podSelector:
        matchLabels:
          app: tripviewer-deployment


