apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "kv-desafio4" # name given to secret provider class
  namespace: "api"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # set to true
    userAssignedIdentityID: "1469c441-27ee-4c8d-aa63-0616bee78f62"  # set to the client id of the key vault addon managed identity fetched above
    keyvaultName: "desafio4-kv" # name of your key vault
    objects:  |
      array:
        - |
          objectName: SQL-SERVER
          objectType: secret
        - |
          objectName: SQL-DBNAME
          objectType: secret
        - |
          objectName: SQL-USER
          objectType: secret
        - |
          objectName: SQL-PASSWORD
          objectType: secret
    tenantId: "72f1a12a-219d-4ba3-9c9b-7c0e1e34114f" # the tenant id of your key vault
  secretObjects:
  - secretName: db-user-pass # name given to our kubernetes secret
    type: Opaque
    data:
    - objectName: SQL-SERVER # must match objectName below
      key: SQL_SERVER # this can be called what you want, this is to reference this object.
    - objectName: SQL-DBNAME # must match objectName below
      key: SQL_DBNAME # this can be called what you want, this is to reference this object.
    - objectName: SQL-USER # must match objectName below
      key: SQL_USER # this can be called what you want, this is to reference this object.
    - objectName: SQL-PASSWORD # must match objectName below
      key: SQL_PASSWORD # this can be called what you want, this is to reference this object.
    